{% set name = "pytest-rerunfailures" %}
{% set version = "16.6" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 29dbfee46f542073c888e0ed4e81c51e15b9096f49a299eb1a759629c601684a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools >=40
    - python {{ python_min }}
  run:
    - packaging >=17.1
    - pytest !=8.2.2,>=8.1
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_rerunfailures

about:
  home: https://github.com/pytest-dev/pytest-rerunfailures
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin to re-run tests to eliminate flaky failures

extra:
  recipe-maintainers:
    - nicoddemus
    - pg-hbk
    - sy-hbk
