{% set name = "pytest-rerunfailures" %}
{% set version = "9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 895ac2a6486c0da0468ae31768b818d9f3f7fceddef110970c7dbb09e7b4b8e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest >=5.0
    - setuptools >=40.0
    - python >=3.5
  run:
    - pytest >=5.0
    - python >=3.5

test:
  imports:
    - pytest_rerunfailures

about:
  home: https://github.com/pytest-dev/pytest-rerunfailures
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin to re-run tests to eliminate flaky failures

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
