{% set name = "pytest-rerunfailures" %}
{% set version = "11.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55611661e873f1cafa384c82f08d07883954f4b76435f4b8a5b470c1954573de

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.7
  run:
    - packaging >=17.1
    - importlib-metadata
    - pytest >=5.3
    - python >=3.7
    - setuptools

test:
  imports:
    - pytest_rerunfailures

about:
  home: https://github.com/pytest-dev/pytest-rerunfailures
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin to re-run tests to eliminate flaky failures

extra:
  recipe-maintainers:
    - nicoddemus
    - pg-hbk
    - sy-hbk
