{% set name = "pytest-rerunfailures" %}
{% set version = "14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a400bcbcd3c7a4ad151ab8afac123d90eca3abe27f98725dc4d9702887d2e92

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools >=40
    - python >=3.8
  run:
    - packaging >=17.1
    - importlib-metadata >=1
    - pytest >=7.2
    - python >=3.8
    - setuptools

test:
  imports:
    - pytest_rerunfailures

about:
  home: https://github.com/pytest-dev/pytest-rerunfailures
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin to re-run tests to eliminate flaky failures

extra:
  recipe-maintainers:
    - nicoddemus
    - pg-hbk
    - sy-hbk
