{% set name = "pytest-rerunfailures" %}
{% set version = "16.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ed4b3a6e7badb0a720ddd93f9de1e124ba99a0cb13bc88561b3c168c16062559

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools >=40
    - python {{ python_min }}
  run:
    - packaging >=17.1
    - pytest >=7.4,!=8.2.2
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_rerunfailures

about:
  home: https://github.com/pytest-dev/pytest-rerunfailures
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin to re-run tests to eliminate flaky failures

extra:
  recipe-maintainers:
    - nicoddemus
    - pg-hbk
    - sy-hbk
