travis:
  secure:
    BINSTAR_TOKEN: jCUs5aQMZJO0V3VgSbHGOGqpgg4GJx+yZQ+05Fryim+eDyeq0tBEMBNTgoe9GmdpqWf+MF8ixeOxXmmJuToUXJvBkUKkV2DD7mQ2g8z+IjBiTH/ly5Sy5MG95uuPlYuEOa7KTCOnDOZfy93L814Wpmp4KBKRXPM4m5Mk4zJhralOnw6S6aE5VK/oa8hX/VkaEzekWi/MYZoYbh7O/mOwCfs/oU/ko/L0rC0PM/EuyDTe0l6g3Kl4m/FRcuJXJKl98VbfikxR1D26nuOGzi8zUXDoy2PLFk91xTcK/Lsexq95LhzN9MuzccuxZDXGI9BSf+VJD5iK7+jpjzY3bhdw6sriAohtHWwg4sEtnaPwvFSr2nub4nDwuxxDxFd9XUebZ/28HIy0/xDfT9SiKRGJbZQyT/do9LN72ViFetcyetW8zebzpY73xGzfpmrqttPK/IeDse59t9Ct+kXtaVx92eb0T5nAlRP2u/21sASyw47mgyju0SKtxUqyjjoS+xjreYuYgNdSDnSZdH7KI5bBIzZ8xl/XW0x3iccc9OaQFxuSNlCNks8bM+ymwPSRmqckbDZxdKTyn+klmSv5N/WJm4zeeLH0VTF+rj8z1gL7yLr0PtqOn8THWvZky5LL+PX7vVr5Hi/yBovUsOHO3d1JHlV69I211OhrPBGDUfjaL9g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
